name: Azure ML Housing Model Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger for pull requests targeting the 'main' branch

jobs:
  # Job 1: Setup Azure CLI and Authentication
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/azure-cli-action@v1
        with:
          azcliversion: '2.41.0'

      - name: Authenticate to Azure
        run: |
          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" > .env
          echo "AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> .env
          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> .env
          echo "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> .env
          source .env
          az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
          az account set --subscription $AZURE_SUBSCRIPTION_ID

  # Job 2: Run the Azure ML Pipeline (Training)
  train_model:
    runs-on: ubuntu-latest
    needs: setup  # Wait for the setup job to complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install azureml-sdk  # Install the Azure ML SDK

      - name: Run Azure ML Pipeline
        run: |
          python src/run_pipeline.py  # Your script that triggers the pipeline in Azure ML Designer

  # Job 3: Model Evaluation (Optional)
  evaluate_model:
    runs-on: ubuntu-latest
    needs: train_model  # Wait for training to complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Evaluate model performance
        run: |
          python src/evaluate_model.py  # You can write a script to evaluate the model on test data

  # Job 4: Model Deployment (Optional)
  deploy_model:
    runs-on: ubuntu-latest
    needs: evaluate_model  # Wait for evaluation to complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Model to Azure
        run: |
          python src/deploy_model.py  # Your deployment script, e.g., to Azure Kubernetes Service (AKS) or Azure Web Service
