name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow for PRs targeting the main branch

jobs:
  setup:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up the Python environment
        with:
          python-version: '3.8'  # Specify the Python version (adjust if necessary)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from your requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: setup  # Ensure this job runs after the 'setup' job completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          pytest  # Run unit tests using pytest (adjust if you're using a different testing tool)

  train:
    runs-on: ubuntu-latest
    needs: test  # Ensure this job runs after the 'test' job completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train the model
        run: |
          python train.py  # Adjust this to your training script

      - name: Save the model
        run: |
          python save_model.py  # Optionally, save the trained model (e.g., using joblib)

  deploy:
    runs-on: ubuntu-latest
    needs: train  # Ensure this job runs after the 'train' job completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy model
        run: |
          python deploy_model.py  # Adjust this to your deployment script
